# Config for Not Found Endpoints
notFound:
  handler: api/modules/redirects.notFound
  timeout: 30
  events:
    - http:
        path: /{proxy+} # catch any path not specified elsewhere
        method: any
        cors: true
